title: "Color"
status: wip
order: 1
context:
  palette:
    - blue
    - blue-light
    - blue-dark
    - purple
    - purple-light
    - purple-dark

  grays:
    - black
    - gray-dark
    - gray
    - gray-light
    - gray-lighter
    - white

  diagramColors:
    - a
    - b
    - c
    - d
    - e
    - f

  semanticColors:
    - brand-primary
    - brand-primary-active
    - brand-secondary
    - brand-secondary-active
    - brand-success
    - brand-info
    - brand-warning
    - brand-danger
    - brand-success-bg
    - brand-info-bg
    - brand-warning-bg
    - brand-danger-bg
    - body-color
    - line-color
    - alt-bg-color

  colorsOnWhite:
    - brand-primary
    - brand-primary-active
    - brand-secondary
    - brand-secondary-active
    - brand-success
    - brand-info
    - brand-warning
    - brand-danger
    - black
    - gray-dark
    - gray

  whiteOnColor:
  - black
  - gray-dark
  - gray

  darkOnColor:
  - gray-light
  - gray-lighter
  - white
